### ISSUE TITLE
Targz Compress Error  - Didn't get expected byte count 

### ISSUE THREAD

**Issue by SudharsanN** [alanhoff/node-tar.gz#47]
We are encountering the below issue when we are using targz().compress(). Below is the stack trace.

Error: Didn't get expected byte count expect: 1703936 actual: 12112951 at decorate (C:\Sudharsan\Workspace\release-v1.11\ce-billing\DowJones.CustomerEngine.Billing\DowJones.CustomerEngine.Billing.Ddp.Edw\node_modules\fstream\lib\abstract.js:67:36)\n at FileReader.Abstract.error (C:\Sudharsan\Workspace\release-v1.11\ce-billing\DowJones.CustomerEngine.Billing\DowJones.CustomerEngine.Billing.Ddp.Edw\node_modules\fstream\lib\abstract.js:61:12)\n at ReadStream. (C:\Sudharsan\Workspace\release-v1.11\ce-billing\DowJones.CustomerEngine.Billing\DowJones.CustomerEngine.Billing.Ddp.Edw\node_modules\fstream\lib\file-reader.js:65:12)\n at emitNone (events.js:91:20)\n at ReadStream.emit (events.js:185:7)\n at endReadableNT (_stream_readable.js:974:12)\n at _combinedTickCallback (internal/process/next_tick.js:74:11)\n at process._tickCallback (internal/process/next_tick.js:98:9)","time":"2017-03-08T20:19:21.188Z","v":0}

We are using version 1.0.5 of tar.gz. We encountered this issue for the first time when the size of the file that we are trying to compress is increased 200 times than the original. Not sure whether that's the reason. 
Can you let us know how to fix this?

**Comment by SudharsanN** [comment]
@here Anyone has an idea on this?

**Comment by SudharsanN** [comment]
@alanhoff  Any idea on this issue?
