### ISSUE TITLE
function request.get().pipe() error

### ISSUE THREAD

**Issue by muzidx** [alanhoff/node-tar.gz#52]
code
```
const request = require('request')
const targz = require('tar.gz')

const read = request.get('https://github.xxx.1.0.0.tar.gz')
const write = targz().createWriteStream('dist')
console.log(read)
console.log(write)

read.pipe(write)
```

node this js file

```
Error: self signed certificate in certificate chain
    at TLSSocket.<anonymous> (_tls_wrap.js:1084:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:188:7)
    at TLSSocket._finishInit (_tls_wrap.js:606:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:436:38)
```

code has some problem for me?

**Comment by muzidx** [comment]
sorry，I got it. should be add .on() before .pipe()  and resolve it. But has some SELF_SIGNED_CERT?
